### ISSUE TITLE
Add copy for age on account creation

### ISSUE THREAD

**Issue by mela124** [schibsted/account-sdk-android#134]
Acceptance criteria:

- Design:
https://app.zeplin.io/project/5ad8456d755b8f2e0da01dcc/screen/5ad84fde35dd53947eea8fa9
- '16' is the value for X
- Show only if it's a new user. Can do it on passwordless as well?

**Comment by Astach** [comment]
the `16` is that just informative or do we have to check it?
If we have to check it, it's a really bad idea to have that hardcoded because if the rule change:
- User will not be informed unless he updates the app.
- User will not understand why he receives an error when he wants to create his account
it means an update of all client apps using the sdk will be needed, and all version not up to date will be broken.

Yes we can do that on passwordless as well.

**Comment by mela124** [comment]
We don't need to check anything except if it's on the required fields which SPiD already throws and error to.

This is just to inform them about that age limit.

**Comment by Astach** [comment]
So what I warned you about in my first comment is still valid if the age limit changes on SPiD side then.
But it doesn't seem important, let's do it.
