### ISSUE TITLE
Clarify the usage of User.bind and allow only one AuthInterceptor

### ISSUE THREAD

**Issue by Swirastlynn** [schibsted/account-sdk-android#223]
### Summary
Schibsted Account injects the same `authorization` header to our backend request for different accounts during one Android app session.

### Environment
- SDK Version: 1.0.0-rc3
- SDK Module: core
- Android Version: 8.1
- Device Info: Pixel 2

### Details
We passed into `user.bind(mBuilder, mValidUrls, false, false);` the same mBuilder for every request to our backend. That's why we send every time the same spid_access_token in `authorization` header. We were not aware about that, it's not usual to create `OkHttp.Builder` every time to handle this case. Fix on our side: instantiate new `OkHttp.Builder` for every `User.bind` with `okHttpClient.newBuilder()`
But we haven't expected such behaviour. We'd like Schibsted Account to be more explicit, for instance we'd like to obtain spid_access_token and inject it to header on our side. Or different, but more explicit solution than the current one (pointing it up in readme?).

### Steps to reproduce
- Log in to Schibsted Account 
`user.persist(mContext);
user.bind(mBuilder, mValidUrls, false, false);`
- log out
 `user.logout`
- log in with different email
`user.persist(mContext);
user.bind(mBuilder, mValidUrls, false, false);`

**Comment by Nexcius** [comment]
Hello @Swirastlynn 

Thanks for getting in touch. The documentation states that 
>You can authenticate your requests by binding a session to an OkHttpClient from the User

I'll make sure we clarify this even further.

Unfortunately, we cannot expose the access token. This is by design, as it has from previous experience led to access and refresh tokens being sent everywhere, which is a huge security issue. I briefly considered checking if a builder already had that interceptor and fail loudly, but that would be during runtime, causing a creash for the client. I'll add a check to ensure only one instance of the interceptor is bound to a builder at a time and log a warning for that. 

Looking at this, led to the discovery of an issue where tokens are not cleared from the interceptor on a manual logout. It's not a big deal, as the tokens are invalid anyhow, but it should be cleared.

**Comment by Nexcius** [comment]
Closed by #234
